#!/usr/bin/env python3
"""Regenerate the source-bound, precompiled StLib module and reader metadata."""

import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[1]
COMPILED = ROOT / "compiled"
OUT = ROOT / "cmd/shen/stlibcompiled"


def generator_digest():
    paths = [
        ROOT / "scripts/generate-stlib.py",
        ROOT / "src/compiler.shen",
        ROOT / "codegen/codegen.go",
        ROOT / "cmd/kl/codegen.go",
        ROOT / "cmd/kl/plugin.go",
        *sorted((ROOT / "kernel/klambda").glob("*.kl")),
    ]
    h = hashlib.sha256()
    for path in paths:
        h.update(str(path.relative_to(ROOT)).encode() + b"\0")
        h.update(path.read_bytes())
    return h.hexdigest()


def run(args, *, cwd, input=None, timeout=240):
    result = subprocess.run(
        args, cwd=cwd, input=input, text=True, capture_output=True, timeout=timeout
    )
    if result.returncode:
        raise RuntimeError(f"{' '.join(map(str, args))}: {result.stderr[-4000:]}\n{result.stdout[-4000:]}")
    return result.stdout


def macro_form_end(source, start):
    depth = 0
    quoted = False
    i = start
    while i < len(source):
        ch = source[i]
        if quoted:
            if ch == '"':
                quoted = False
        elif source.startswith("\\\\", i):
            newline = source.find("\n", i)
            i = len(source) if newline < 0 else newline
            continue
        elif ch == '"':
            quoted = True
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise RuntimeError("unterminated defmacro")


def main():
    source = (ROOT / "cmd/shen/stlib.go").read_text()
    order = re.findall(r'"(stlib/[^\"]+)"', source.split("var stlibInstallOrder", 1)[1].split("}", 1)[0])
    if not order:
        raise RuntimeError("stlibInstallOrder is empty")
    packages = []
    parts = []
    macro_sources = []
    for name in order:
        data = (ROOT / "cmd/shen" / name).read_bytes()
        parts.append(data + b"\n")
        text = data.decode().replace("\r\n", "\n")
        macro = re.search(r"^\(defmacro\s", text, re.M)
        if macro:
            prefix = text[:macro.start()]
            form = text[macro.start():macro_form_end(text, macro.start())]
            excerpt = prefix + form + ("\n)" if text.lstrip().startswith("(package ") else "")
            macro_sources.append("\n".join(line.rstrip() for line in excerpt.splitlines()) + "\n")
        match = re.search(rb"^\(package\s+([^\s()]+)", data, re.M)
        if match:
            package = match.group(1).decode()
            if package not in packages:
                packages.append(package)
    stlib = b"".join(parts)
    digest = hashlib.sha256(stlib).hexdigest()

    prefix = f"_stlib_gen_{os.getpid()}"
    paths = {suffix: COMPILED / f"{prefix}.{suffix}" for suffix in ("shen", "kl", "tmp", "go", "fns")}
    try:
        paths["shen"].write_bytes(stlib)
        preamble = (COMPILED / "precompile.kl").read_text().split('(bootstrap "_in.shen")', 1)[0]
        script = preamble
        script += f'(bootstrap "{prefix}.shen")\n'
        script += f'(do (compile-file "{prefix}.kl" "{prefix}.tmp") ())\n'
        script += f'(let Cg (make-code-generator) (bc->go Cg "StlibMain" true "{prefix}.tmp" "{prefix}.go"))\n'
        script += f'(emit-arities "{prefix}.kl" "{prefix}.fns")\n'
        for package in packages:
            for attr in ("shen.external-symbols", "shen.internal-symbols"):
                script += f'(get {package} {attr} (value *property-vector*))\n'

        with tempfile.TemporaryDirectory(prefix="shen-go-stlib-gen-") as tmp:
            binary = Path(tmp) / "kl"
            run(["go", "build", "-o", str(binary), "./cmd/kl"], cwd=ROOT)
            output = run([str(binary)], cwd=COMPILED, input=script)

        prompts = [m.group(2) for line in output.splitlines() if (m := re.match(r"^(\d+) #> (.+)$", line))]
        values = prompts[-2 * len(packages):]
        if len(values) != 2 * len(packages) or any(not (v.startswith("(") and v.endswith(")")) for v in values):
            raise RuntimeError(f"cannot read package metadata from KL output:\n{output[-4000:]}")
        if "Error(" in output or "read error:" in output:
            raise RuntimeError(f"StLib bootstrap failed:\n{output[-4000:]}")

        raw = paths["go"].read_text().replace("package main\n", "package stlibcompiled\n", 1)
        raw = "// Code generated by scripts/generate-stlib.py; DO NOT EDIT.\n" + raw
        raw += '''\nvar ns2_1set Obj
var try_1catch Obj

func Install(e *ControlFlow) Obj {
    ns2_1set = PrimFunc(MakeSymbol("defun"))
    try_1catch = PrimFunc(MakeSymbol("try-catch"))
    return Call(e, StlibMain)
}
'''
        OUT.mkdir(exist_ok=True)
        (OUT / "stlib.go").write_text(raw)
        (OUT / "macros.shen").write_text("\n".join(macro_sources))

        rows = []
        for i, package in enumerate(packages):
            rows.append((package, values[2 * i][1:-1].split(), values[2 * i + 1][1:-1].split()))
        def sl(items):
            return "[]string{" + ", ".join(json.dumps(item) for item in items) + "}"
        metadata = [
            "// Code generated by scripts/generate-stlib.py; DO NOT EDIT.",
            "package stlibcompiled", "",
            "const SourceSHA256 = " + json.dumps(digest),
            "const GeneratorSHA256 = " + json.dumps(generator_digest()),
            "const Arities = " + json.dumps(paths["fns"].read_text()),
            "type PackageSymbols struct { Name string; External, Internal []string }",
            "var Packages = []PackageSymbols{",
        ]
        for package, external, internal in rows:
            metadata.append("{" + json.dumps(package) + ", " + sl(external) + ", " + sl(internal) + "},")
        metadata += ["}", ""]
        (OUT / "metadata.go").write_text("\n".join(metadata))
        run(["gofmt", "-w", str(OUT / "stlib.go"), str(OUT / "metadata.go")], cwd=ROOT)
        print(f"generated StLib from {len(order)} files, SHA-256 {digest}")
    finally:
        for path in paths.values():
            path.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
